- docs/source/dev/development.rst
This will essentially be our upgrade to nodejs 0.12. We can cross the deployment bridge when we come to that, but with Chef it's easy and with Docker we can essentially just do this.
> Add node v0.12 install instructions

- .gitignore
- docs/source/dev/development.rst
- package.json
- tests/test.js
```
(timesync)iankronquist@puppettop:(timesync)(ian/istanbul-sokaklari) → npm run coverage
> timesync@0.0.0 coverage /Users/iankronquist/gg/timesync
> export DATABASE=mocha export PORT=8851 && rm -f test.sqlite3 && knex --env mocha migrate:latest && istanbul cover _mocha -- tests
Using environment: mocha
Batch 1 run: 1 migrations 
/Users/iankronquist/gg/timesync/migrations/20150101000000_00.js
App now listening on 8851
Endpoints
GET /times
✓ should return all times in the database
GET /times/:id
✓ should return times by id
✓ should fail with Object not found error
GET /users
✓ should return all users in the database
GET /activities
✓ should return all activities in the database
GET /activities/:slug
✓ should return activities by slug
✓ should fail with invalid slug error
GET /projects
✓ …
```
> Add Istanbul test coverage tracker

- tests/activities.js
- tests/projects.js
- tests/times.js
- tests/users.js
``expect(a === b)`` is meaningless. What we really want, in order to test that equality, is ``expect(a).to.be(b)``: https://github.com/Automattic/expect.js#api
> Make tests actually check for equality

- docs/source/dev/development.rst
- package.json
- scripts/latte.sh
It runs the linter and then the tests, before printing test coverage.
Is there a better order?
> Add latte command

- README.md
- docs/source/dev/development.rst
- package.json
nodemon will watch the directory, and restart node every time a file
is saved. This means no more forgetting to restart your server after
making changes!
> add nodemon

- tests/test.js
This allows tests to fail and not break the next round of tests. Now, for every test, it will BEFORE THE TEST clear the database and reload the fixtures.
> rearrange before/after database hooks

- knexfile.js
- src/app.js
- tests/test.js
This also reduces the number of database connections from two plus one per test run to only one for the entire run.
> Speed up tests with in-memory database

- .jscsrc
- tests/helpers.js
- tests/times.js
This means we won't need to keep wrapping things in ``jscs:disable`` and ``jscs:enable``. Should have googled this before.
> set jscs to allow snake_case properties

- src/projects.js
- tests/projects.js
Currently if you POST a string to the slug field, it'll crash the server when it attempts to run a ``.filter`` on it. Check your datatypes, folks!
> add bad datatype checking to POST projects/

- docs/source/dev/development.rst
- knexfile.js
- migrations/20150101000000_00.js
- package.json
- scripts/create-account.js
- scripts/load_fixtures.js
- src/app.js
- tests/fixtures/test_data.json
This required updating the fixtures as well, since many of them took
advantage of sqlite being lazy and allowing bad foreign keys.
It also moves everything over to the NODE_ENV variable, which is the
"blessed" way of doing this kind of config.
> add production database environment

- src/times.js
- tests/times.js
Allow a user to select times only within a given date range, using start and end query parameters. Fixes issue #131.
> Select times within a given date range

- .gitmodules
resolves #159 
How to initialize the new API (assuming a clean clone of the ``timesync-node`` repo on the ``elijah/readd-api`` branch [but it should work just fine on an existing clone])
```
[timesync-api/]$ git submodule init .  # This initializes the git submodules in the repo (there's only one)
Submodule 'timesync-api' (https://github.com/osuosl/timesync.git) registered for path 'timesync-api'
[timesync-api/]$ git submodule update .  # This clones the submodule and sets it to be
Cloning into 'timesync-api'...
remote: Counting objects: 1028, done.
remote: Compressing objects: 100% (32/32), done.
remote: Total 1028 (delta 158), reused 135 (delta 135), pack-reused 861
Receiving objects: 100% (1028/1028), 146.66 KiB | 0 bytes/s, done.
Resolving deltas: 100% (542/542), done.
Checking …
```
> re-added timesync gitsubmodule

- src/projects.js
- tests/projects.js
The tests related to /projects/*?include_revisions pass now.
A few other tests (once merged, the include_revisions on the times endpoint for instance) do not pass yet, that's why this merge is going into ``elijah/includ_revisions`` and not ``develop``.
> Include Revisions on the Projects endpoint

- tests/times.js
Last merge introduced an error for a previously-existing typo. This clears the linter error.
> Fix very minor linter error.

- src/activities.js
- src/projects.js
- src/times.js
Calling rollback() on a transaction causes the catch function on ``knex.transaction()`` to always be called. By removing the server error blocks from the inner catch blocks, such that these only contain calls to rollback(), we can prevent the "cannot set headers after they are set" error that occurs due to attempting to send an error twice.
> Fix "cannot set headers after they are set" error by cleaning up transactions.

- docs/source/design/libraries.rst
- src/activities.js
- src/times.js
As a result of rebasing #206, two small bugs were introduced. 1) A function which used transactions did not call ``commit()`` at the end, which would have prevented the database from being updated. 2) Two functions use the root knex object inside of a transaction for a select call, which one might think appears to be legal, but in fact will cause the application to hang indefinitely. This fixes those bugs.
> Fix small bugs introduced when merging branches earlier.

- README.md
When I use the snippet mentioned in the README for generating a web token (assuming my username is `ichait` and password is `pass`) - 
```
$ curl -X POST -d '{"auth":{"type":"password","ichait":"username","password":"pass"}}' -H "Content-Type: application/json" http://localhost:8000/v1/login
```
I get the following error - 
```
{"status":401,"error":"Authentication failure","text":"Missing credentials"}%
```
And when I use the following snippet it works fine -
```
$ curl -X POST -d '{"auth":{"type":"password","username":"ichait","password":"pass"}}' -H "Content-Type: application/json" http://localhost:8000/v1/login
```
Generates a web token - 
```
{"token":"eyJ0eXAiOiJKV1QiLCJhbGciOiJITUFDLVNIQTUxMiJ9.eyJpc3MiOiJ0aW1lc3luYy1sb2NhbCIsInN1YiI6ImljaGFpdCIsImV4cCI6MTQ1NzU3NTg2NzkxOCwiaWF0IjoxN …
```
> Fixed ordering of parameters.

- README.md
- package.json
- scripts/pg_docker.sh
So we had a bit of difficulty with the /users endpoint and postgres.
To hopefully sidestep this problem later on I added a command:
`npm run test_pg_docker`
This will automatically spin up a docker container with postgres
installed. It will then spin up a database and run the postgres-backed
tests suite.
Notes:
- You should be able to run docker as a non-super-user for this to run
correctly. (add yourself to the docker group)
- The docker daemon has to be running.
- The script has a built in 10 second waiting period between spinning
up the container and moving on. This is so postgres has ample time
to create your database. If you get errors related to your table not
being created you'll probably want to bump that time up a bit.
> Added a postgres docker testing container command

- migrations/20150101000000_00.js
- src/authenticatedRequest.js
- src/helpers.js
- src/login.js
- src/projects.js
- src/times.js
- tests/fixtures/README.md
- tests/fixtures/test_data.json
- tests/helpers.js
- tests/projects.js
- tests/times.js
Projects have an optional ``default_activity`` field. When a time is posted with a project with a default activity but no activities, it is given the default activity. If the time is posted with a project with no default activity and no activities, an error is returned. If the time is posted with activities, the project's default activity is ignored. If the project's default activity is changed, it has no impact at all on the time (even if the time was created with the default activity). Fixes #106.
> Add default activities for projects.

- src/projects.js
Should fix #267. The issue seems to have been a timing issue: we passed knex('projectslugs').del() into Promise.all() alongside all the .insert() promises. The issue is that Promise.all() executes all the promises simultaneously, not waiting for one to finish to begin the next, so sometimes it started attempting to insert slugs before the previous ones had been removed.
> Separate out projectslug deletion to prevent timing errors.

- src/app.js
- src/errors.js
- tests/test.js
Fixes #271.
Adds a middleware that checks for errors, and if there is an error, it returns a 400. Otherwise, it continues as normal.
> Fix crashes on receiving bad json.

- package.json
- src/app.js
This was going to be part of a larger audit (following [Express's security guidelines](http://expressjs.com/en/advanced/best-practice-security.html)), but it looks like we've already done a pretty good job at preventing a lot of threats. Introducing [helmet](https://www.npmjs.com/package/helmet) was the only significant thing I could add.
> Add protective HTTP headers for increased security.

- package.json
- src/app.js
Fixes #272. 
Turns out express provides a middleware for this to make it easy.
> Add CORS header support.

- src/projects.js
- tests/projects.js
fixes issue #289
1. Run ``npm test``.
2. Create a testing instance of TimeSync, then (after authenticating) make a request to ``/projects?user=tschuy``.
1. The two new tests should pass.
2. You should see a list only of the projects to which tschuy belongs.
@osuosl/devs
> Add user parameter to projects.

- src/activities.js
> Remove template strings to prevent crashes in old versions of Node.js.

- src/activities.js
- src/projects.js
- src/times.js
- tests/activities.js
- tests/projects.js
- tests/times.js
Fixes #315.
1. `npm install`
2. `npm run latte`
"382 passing (12s)"
@osuosl/devs
> Make create endpoints return *_at field and project update return users

- src/times.js
- tests/test.js
I noticed this while I was working on a different issue. If you look at lines 666-688, it becomes clear that the array passed to `insert()` will always be truthy (note that an empty array is truthy).
Either the user passed in an `activities` array (in which case `time.activities` will be truthy, and the first branch will be taken), and the array passed to `insert()` is the result of calling `helpers.checkActivities()` on the `activities` array, which will only resolve with an array itself.
Or the user didn't pass in an `activities` array (in which case it will be `undefined`, and the second branch is taken), and the app retrieves the `default_activity` from the project (returning an error if it's null), and passes its ID to `insert()`.
In either case `activityIds` will always be truthy, …
> Remove if branch which was unreachable.
