docs/source/design/draft_api.rst
docs/source/design/draft_models.rst

This changes the API significantly.
This puts the ADD, UPDATE request bodies into the body of the request as JSON.
It also removes the ext field (why is this a thing), and makes errors only show upon error. (This is how most APIs I'm familiar with implement errors.)
It also specifies the response bodies of API requests more fully.

New draft API

---

.jshintrc
src/checkins.js

See: https://github.com/osuosl/timesync/pull/8#commitcomment-11777545

Enforce curly braces

---

README.md

Also added _static directory to docs b/c of a sphinx error.
Since this is empty I added a .gitkeep file

Added more usage info to readme

---

package.json

Ian said we should probably udpate our dependencies: https://david-dm.org/osuosl/timesync#info=dependencies&view=table
I'm inclined to agree. This looks good to me, so since tests pass, I'm +1'ing it.

Update package.json and move things to dev deps

---

README.md

I was going to include this with my other commits but I guess they got merged already. If you think this is ugly or don't trust the service, fine, I don't care.

Add dependency status to README

---

scripts/load_fixtures.js

Remove unused variables which code climate is complaining about.
Yet another silly pr.
@tschuy r?

Fix minor code climate issues

---

package.json

Don't keep what you don't use.

Remove supertest from package.json

---

.jscsrc
src/activities.js
src/errors.js
src/projects.js
src/times.js
tests/activities.js
tests/projects.js
tests/test.js
tests/times.js
tests/users.js

Because it's in the AirBnB guide, which is our guide.

camelCase allTheThings

---

migrations/20150101000000_00.js
package.json
tests/fixtures/test_data.json
tests/users.js

Modified user test to contain password and active fields

---

package.json

Add valid-url to package.json

---

package.json
scripts/load_fixtures.js

lint scripts

---

src/errors.js
tests/errors.js
tests/test.js

Add auth errors, auth error tests

---

src/auth/local.js
tests/login.js

Change passport auth block

---

docs/source/design/draft_models.rst
src/helpers.js
tests/helpers.js

This fixes #100 .
There are comments in the the regex for what it SHOULD match. If you think of a test case that should be added, please mention it.

Add slug regex checks

---

package.json
src/errors.js
src/helpers.js
src/projects.js
tests/activities.js
tests/errors.js
tests/helpers.js
tests/projects.js
tests/test.js
tests/times.js

Fixes https://github.com/osuosl/timesync-node/issues/29.
These tests are a work in progress -- I have the "success" tests written, and the "it doesn't add things" written, but not the error message tests.

POST /projects

---

README.md
docs/source/dev/development.rst

This will save us countless seconds going forward. @osuosl/devs

Added docs about running a subset of the tests with -- -g <substring>

---

src/errors.js
src/helpers.js
src/projects.js
tests/helpers.js
tests/projects.js

Updates a given project based on a given slug.
Testing:
```
$ npm test
```
Tests live in ``tests/projects.js`` under ``describe('POST /projects/:slug', ...``

POST projects/:slug

---

src/errors.js

Error to return upon a refusal of a delete request.

Add delete failure to list of errors

---

src/errors.js
src/projects.js
tests/helpers.js
tests/projects.js

project/:slug DELETE endpoint

---

.jscsrc
migrations/20150101000000_00.js
scripts/create-account.js
scripts/load_fixtures.js
src/activities.js
src/app.js
src/auth/local.js
src/errors.js
src/helpers.js
src/projects.js
src/times.js
tests/activities.js
tests/errors.js
tests/fixtures/test_data.json
tests/helpers.js
tests/login.js
tests/projects.js
tests/test.js
tests/times.js

Decrease from 4 to 2 space indentation. Fixed #132.

Decrease indentation

---

src/errors.js

The query string tests have a new error to check against.
https://github.com/osuosl/timesync-node/blob/tristan/query-string-tests/tests/times.js#L118

New query error

---

README.md

Two minor grammar/punctuation edits.

Minor grammar and punctuation edits to README

---

src/activities.js
tests/activities.js

Fixes https://github.com/osuosl/timesync-node/issues/32
This appears to have been forgotten from an earlier sprint.

POST /activities

---

src/errors.js
src/times.js
tests/times.js

Activities query parameter

---

docs/source/design/libraries.rst

Fixes #121. Documentation for developers on using RequestJS, specifically within timesync.

Added documentation on RequestJS.

---

migrations/20150101000000_00.js
package.json
src/activities.js
src/helpers.js
src/projects.js
src/times.js
tests/activities.js
tests/fixtures/test_data.json
tests/helpers.js
tests/projects.js
tests/times.js

Fixes #183. Adds UUID and Revision numbers to all objects.

Add UUIDs and Revision numbers

---

scripts/load_fixtures.js
src/times.js
tests/times.js

Allow times to be filtered by project.

---

package.json
scripts/clear-database.js

Once we get a testing env up for docker, I'll redo this a little to clear postgres as well.

add clear-database command

---

src/times.js
tests/times.js

The developers need to do a better job reviewing each others' code. Commented out tests were merged into develop. Afterwards there was a regression which was not detected by the tests. I think that the developers should take a moment to reflect on why this mistake happened and what steps can be taken, automatically or manually, to prevent its recurrence.

Uncomment tests

---

migrations/20150101000000_00.js
src/activities.js
src/projects.js
src/times.js
tests/activities.js
tests/fixtures/test_data.json
tests/projects.js
tests/times.js

De-duplicated insert/update code and make objects immutable

---

migrations/20150101000000_00.js
src/activities.js

Soft delete activities

---

src/projects.js

Soft delete projects

---

src/times.js
tests/times.js

These are the initial tests for soft-deleting times (DELETE ``/times/:uuid``)

Soft-deleting times

---

src/projects.js

Fixed bug where updating a project failed to carry over roles.

---

src/projects.js
tests/projects.js

Ensure we can't delete slugs from a project.

---

migrations/20150101000000_00.js
src/projects.js
tests/.eslintrc
tests/fixtures/test_data.json
tests/projects.js

Remove project owner, replace with manager in full.

---

src/projects.js

Fix some code that had been missed previously in #215.

Remove remaining references to owner.

---

package.json
src/activities.js
src/app.js
src/auth/ldap.js
src/auth/local.js
src/auth/token.js
src/helpers.js
src/log.js
src/login.js
src/projects.js
src/times.js

This will prevent failures to solve problems on the staging (and, in the future, production!) instance by providing full access and error logging on the application, including timestamps, etc.

Add console and file logging.

---

migrations/20150101000000_00.js
tests/fixtures/test_data.json

Add the new user model.

---

README.md

Follow-up on #247, fix a minor typo in one line.

Fix authentication command in README.

---

.travis.yml
knexfile.js
scripts/create-account.js
setup.sh

Script will install dependencies, run migrations, and create root account.

Add setup script for production.

---

src/projects.js
tests/fixtures/README.md
tests/fixtures/test_data.json
tests/projects.js

Add member lists to the /projects endpoints.

---

src/activities.js
src/authenticatedRequest.js
src/errors.js
src/helpers.js
src/login.js
src/projects.js
src/times.js
src/users.js
tests/activities.js

Fixes #259 by checking whether data has already been sent before sending any errors.

Add errors.send() helper function to prevent "cannot set headers" error.

---

src/errors.js
src/helpers.js
src/users.js
tests/helpers.js
tests/users.js

Check username uniqueness on create user.

---

src/activities.js
src/projects.js
src/users.js
tests/activities.js
tests/projects.js

Prevent duplication of activity and project slugs and names.

---

src/app.js
src/users.js
tests/test.js

Set API version, and fix permissions issues on user endpoint.

Some minor final changes before release.

---

src/projects.js
tests/projects.js

Fix Server Error when creating a project with a bad username.

---

.gitignore
.travis.yml
CHANGELOG.md
LICENSE.md
README.md
migrations/20150101000000_00.js
package.json
scripts/create-account.js

Clean up and improve the gitignore, travis file, readme, migrations, package.json, and scripts, as well as add a changelog and license file.

Clean up and simplify scripts and metadata.

---

README.md

Fixed order of build instructions in README

---

src/projects.js
src/times.js
tests/activities.js
tests/projects.js
tests/times.js
tests/users.js

A quick solution to ameliorate #270 (and something we should have been doing this whole time *anyway*), but it won't ultimately be the fix.

Check for nonexistent time and project when updating.

---

CHANGELOG.md
README.md

Some documents still incorrectly read version 1 instead of 0.

Fix readme and changelog to show correct version.

---

src/activities.js
src/projects.js

Make activities and projects check only for active times.

---

.github/PULL_REQUEST_TEMPLATE.md

Create a PR to this project for a change.
The template provided in PULL_REQUEST_TEMPLATE.md should be pre-filled into the PR description for you.
@osuosl/devs

Add Github PR template.

---

src/times.js

fixes issue #270
1. Attempt to update several times.
Should not see any 404s when the slug provided is valid and exists.
@osuosl/devs

Fix faulty join causing 404 on update times.

---

src/activities.js
src/projects.js
src/users.js
tests/activities.js
tests/projects.js
tests/times.js
tests/users.js

Fixes the mess that our tests are largely in right now, as a result of the rather natural evolution of the files and the lack of any consistent standard or guideline.
1. Run tests (``npm run test``).
2. Read tests.
1. They still work just as well, and even a little faster.
2. Much of the boilerplate is removed, each test has a standardized form, and each file has one source of truth of test data (allowing easy changes later).
@osuosl/devs

Refactor, reduce, and refine tests.

---

knexfile.js

fixes issue #298 
1. Run `NODE_ENV=production_sqlite npm run migrations`
Not this error:
```
Error: Cannot find module './dialects/sqite3/index.js'
```
@osuosl/devs

Fixed typo in knexfile.js

---

tests/projects.js

1. Run tests
No test errors
@osuosl/devs

Replace equal() with have.same.members() where appropriate.

---

README.md
src/projects.js
tests/activities.js
tests/errors.js
tests/fixtures/README.md
tests/fixtures/test_data.json
tests/helpers.js
tests/login/ldap.js
tests/login/ldapserver.js
tests/login/password.js
tests/login/token.js
tests/projects.js
tests/test.js
tests/times.js
tests/users.js

Use generic names that describe purpose in tests.

---

CHANGELOG.md
package.json

v0.1.1 release.

---

CHANGELOG.md
README.md
knexfile.js
package.json
src/activities.js
src/projects.js
src/times.js
src/users.js
tests/activities.js
tests/errors.js
tests/fixtures/README.md
tests/fixtures/test_data.json
tests/helpers.js
tests/login/ldap.js
tests/login/ldapserver.js
tests/login/password.js
tests/login/token.js
tests/projects.js
tests/test.js
tests/times.js
tests/users.js

v0.1.1 release

---

src/errors.js

fixes issue #
1. Run `npm run latte`
```
$ npm run latte
...
378 passing (21s)
```
@osuosl/devs

Fixed error formatting for errorAuthenticationTypeFailure

---

migrations/20150101000000_00.js
scripts/update-database-uuid-links.js
src/projects.js
src/times.js
tests/fixtures/test_data.json
tests/projects.js
tests/times.js

Fixes #311.
1. Run `npm test`
All tests pass.
@osuosl/devs

Use UUIDs for references between objects instead of IDs.

---

CHANGELOG.md
package.json
setup.sh

1. Run `npm run latte`
```
382 passing (23s)
```
@osuosl/devs

Prepare for v0.1.2 release.

---

src/errors.js
tests/activities.js
tests/projects.js
tests/times.js

Partially addresses issue in osuosl/timesync-api#70.
1. `npm test`
All tests pass.
@osuosl/devs

Changed "Bad Query Value" to mixed case.

---

.travis.yml

Update TravisCI to use NodeJS v6.9 LTS. This matches our production environments better.
1. Travis runs its own tests.
Build success in Travis.
@osuosl/devs

Update NodeJS version in travis.
